### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by TimoStahl** [BlueTeck/kanboard_plugin_boardcustomizer#1]

**Comment by TimoStahl** [comment]
![image](https://user-images.githubusercontent.com/1961634/60758678-45135700-a01a-11e9-9c9d-23290daaddb7.png)

**Comment by TimoStahl** [comment]
![image](https://user-images.githubusercontent.com/1961634/60758686-6f651480-a01a-11e9-8bb0-0afb13ba9a6e.png)

**Comment by timdonovanuk** [comment]
Although pictures are worth a thousand words, 10 mins of time hunting how to use this plugin could be saved by a few words - "To use kanboard_plugin_boardcustomizer after installation, go to 'My Profile' and select My display settings" :)

Awesome plugin BTW. Thanks!

**Comment by TimoStahl** [comment]
Done 😄
