### ISSUE TITLE
Mysterious problems

### ISSUE THREAD

**Issue by DudeHe11** [BlueTeck/kanboard_plugin_boardcustomizer#10]
Hello, I encountered several problems.
1. If you put it into the plugins folder via git clone, it doesn’t pick up this plugin, I fixed it by renaming the folder from kanboard_plugin_boardcustomizer to boardcustomizer

2. After picking it up, the user window disappears and therefore you cannot enter the management, but even if you leave the user window open, there is still no plugin menu.

Sorry for the crooked English (Google Translate)

![image](https://github.com/TimoStahl/kanboard_plugin_boardcustomizer/assets/165657540/ae13c06a-65fc-436d-bfeb-5da8dac08802)
![image](https://github.com/TimoStahl/kanboard_plugin_boardcustomizer/assets/165657540/a21ca777-aa71-4307-ac8d-77525f6481cf)

kanboard 1.2.21

**Comment by TimoStahl** [comment]
https://github.com/TimoStahl/kanboard_plugin_boardcustomizer?tab=readme-ov-file#installation

> Create a folder plugins/**Boardcustomizer**
> Copy all files under this directory

**Comment by DudeHe11** [comment]
Hello, almost exactly what I said, but I solved this problem, I needed to change strictly plugins_installers "off" to "on" in the kanboard config, and then everything worked

**Comment by DudeHe11** [comment]
Thanks
