### ISSUE TITLE
Show some metadata field on the card

### ISSUE THREAD

**Issue by alaner2k** [BlueTeck/kanboard_plugin_boardcustomizer#3]
Good day,

Could you pls advise is it ever possible to put some of my metadata (ex wonderful MetaMagik plugin) right on the task card? It would customize the card with no limits practically!

Tks in advance!

**Comment by TimoStahl** [comment]
Hey,

it would be possible, but I think this feature should be implemented in Metamagik, maybe you could create a ticket over there.

Regards,
Timo
